backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" #
collections:
  - name: "docs" # Used in routes apiEndpoint
    label: "docs" # Used in the UI
    folder: "docs/tutorial-basics" # The path to the folder where the files are stored
    create: true # Allow users to create new files in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new files (optional)
    fields:
      - { label: "Title", name: "title", widget: "string" }
