local_backend: true

backend:
  name: github
  repo: niravbhuva99/cms-thesis-project
  branch: main

media_folder: "static/img" # images stored in the repo under static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: thesis
    label: Thesis
    format: frontmatter
    folder: docs/thesis
    extension: mdx
    create: true
    identifier_field: title
    fields:
      - { label: Title, name: title, widget: string, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Slug, name: slug, widget: string, required: false }
      - {
          label: Sidebar Position,
          name: sidebarPosition,
          widget: number,
          required: false,
        }
      - { name: description, label: Description, widget: text, required: false }
      - {
          name: imageUploader,
          label: Image Uploader,
          widget: string,
          required: false,
        }
      - { label: Body, name: body, widget: mdx }
